// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// //
/// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZO5HYSPdoiIwkLJD0uzGJimBtw_Bv_H8',
    appId: '1:940390359029:web:583f70cf2e388279218abc',
    messagingSenderId: '940390359029',
    projectId: 'instagram-e1231',
    authDomain: 'instagram-e1231.firebaseapp.com',
    storageBucket: 'instagram-e1231.firebasestorage.app',
    measurementId: 'G-NYYBC0GJQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKifGg0DxocjVv4TVBsq8ubRdI80TrAC8',
    appId: '1:940390359029:android:5c79e2fd73fb639c218abc',
    messagingSenderId: '940390359029',
    projectId: 'instagram-e1231',
    storageBucket: 'instagram-e1231.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDk7S-Vh2BiOfKWVwkH6bf14jFMuh4Im4',
    appId: '1:940390359029:ios:44902f31c0f582d1218abc',
    messagingSenderId: '940390359029',
    projectId: 'instagram-e1231',
    storageBucket: 'instagram-e1231.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDk7S-Vh2BiOfKWVwkH6bf14jFMuh4Im4',
    appId: '1:940390359029:ios:44902f31c0f582d1218abc',
    messagingSenderId: '940390359029',
    projectId: 'instagram-e1231',
    storageBucket: 'instagram-e1231.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZO5HYSPdoiIwkLJD0uzGJimBtw_Bv_H8',
    appId: '1:940390359029:web:c3b5ffda0b85e868218abc',
    messagingSenderId: '940390359029',
    projectId: 'instagram-e1231',
    authDomain: 'instagram-e1231.firebaseapp.com',
    storageBucket: 'instagram-e1231.firebasestorage.app',
    measurementId: 'G-FM0FDQZ29S',
  );
}
